
target 'HBDNavigationBar_Example' do
  pod 'HBDNavigationBar', :path => '../'
  
  target 'HBDNavigationBar_Tests' do
    inherit! :search_paths
    
    
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "amd64"
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end
end
