
platform :ios, '12.0'

target 'SwiftDemo' do

  use_frameworks!

  pod 'HBDNavigationBar/Swift', :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
